### ISSUE TITLE
Priority Task list

### ISSUE THREAD

**Issue by OUTtest** [OUTtest/FLOW_PLANET#5]
- [ ]  1. *타이머 이식 (타이머 시간 폰트 적합한거 찾아서 부여 예정)
- [ ]  2. *타이머 이식 후 각 감지마다(소리, 움직임, 수면) 처리해야하는 작업 만들기
- [ ]  3. 타이머 종료후 점수판 항목 만들기 (점수 매기는 기준은 재량껏)
- [ ]  4. *점수판 종료후 탐사보고서 작성항목 만들기
- [ ]  5. *통계항목에서 시간별로 표시되는 오브젝트 다르게 만들기
- [ ]  6. 애니메이션 이식

*표시 항목은 필수로 처리해야할 것
